api_platform:
    title: Scaryview API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 12
        pagination_client_enabled: true
    collection:
        pagination:
            enabled_parameter_name: pagination